### ISSUE TITLE
Support French retrieval of Resolution, Recommendation, Declaration and Meeting

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#27] opened 2022-06-08 08:08 UTC
The fetching syntax should allow both English and French, and retrieve the identical bibliographic item. This is because BIPM is a French-first organization.

In rendering the title/contents, the language should respect the rendering options.

Originally from @manuel489 (https://github.com/metanorma/bipm-si-brochure/issues/169):
> French references don't fetch when a tilde is present in the identifier

* "Résolution" => English Resolution
* "Réunion" => English Meeting
* "Déclaration" => English Declaration
* "Recommandation" => English Recommendation

**Comment by andrew2net** [comment] 2022-06-08 09:54
@ronaldtse it was implemented in v 1.11.6

**Comment by ronaldtse** [comment] 2022-06-08 10:38
Thanks @andrew2net !

**Comment by manuel489** [comment] 2022-06-08 13:58
Could anyone else confirm my outcome, please?

**Comment by anermina** [comment] 2022-06-10 23:28
@andrew2net which relaton-bipm version are you using?
I am currently getting the same output as Manuel.

**Comment by manuel489** [comment] 2022-06-11 02:55
Maybe this is a metanorma-bipm issue, I have opened a ticket for @opoudjis there.

**Comment by andrew2net** [comment] 2022-06-11 10:55
> which relaton-bipm version are you using?

@anermina I use v 1.11.8

**Comment by opoudjis** [comment] 2022-06-13 10:37
First:

`relaton fetch` is NOT a useful test of this, because the functionality is invoked in fetch_async.

I do not know what is happening, but under Metanorma operating conditions, which means caching and asynchronous fetching, "CGPM Résolution 1889-00" is NOT being recognised at all. And @andrew2net needs to debug this in the context of fetch_async. I can't.

Second:

What is required here by @ronaldtse refusing to accept i18n of the identifier after fetching is a bilingual identifier. That is not being fetched at all.

bundle exec relaton fetch "CGPM Résolution 1889-00"

is fetching:

````
<bibitem id="CGPMResolution(1889)">
  <fetched>2022-06-13</fetched>
  <title format="text/plain" language="en" script="Latn">Sanction of the international prototypes of the metre and the kilogram</title>
  <title format="text/plain" language="fr" script="Latn">Sanction des prototypes internationaux du mètre et du kilogramme</title>
  <uri type="src">https://www.bipm.org/en/committees/cg/cgpm/1-1889/resolution-</uri>
  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-en/meeting-01.yml</uri>
  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-fr/meeting-01.yml</uri>
  <uri type="pdf">https://www.bipm.org/documents/20126/17314988/CGPM1.pdf/ab69792a-2e5e-2040-14d0-11464bc9414c</uri>
  <docidentifier type="BIPM" primary="true">CGPM Resolution (1889)</docidentifier>
  <docnumber>CGPM Resolution (1889)</docnumber>
  <date type="published">
    <on>1889-09-28</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bureau International des Poids et Mesures</name>
      <abbreviation>BIPM</abbreviation>
      <uri>www.bipm.org</uri>
    </organization>
  </contributor>
  <language>en</language>
  <language>fr</language>
  <script>Latn</script>
</bibitem>
````

I need there to be a 

 `CGPM Résolution (1889)`

somewhere in the record. Right now, there is not.

Do NOT give me different output if I request "CGPM Résolution 1889-00" or "CGPM Resolution 1889-00". Manuel and Ronald seem to assume you should: that is completely wrong. There is only one bibliographic resource, with language variants inside.

Instead, give me three identifiers:

````  
<docidentifier type="BIPM" primary="true">CGPM Resolution (1889)</docidentifier>
<docidentifier type="BIPM" primary="true" language="en">CGPM Resolution (1889)</docidentifier>
<docidentifier type="BIPM" primary="true" language="fr">CGPM Résolution (1889)</docidentifier>
````

The notion of a language-specific document identifier is insane, but... I don't think it's wrong. I'll add language and script to the grammar for docidentifier.

@andrew2net I need you to test this on branch fix/relaton-i18n of metanorma-bipm, so ensure  that CGPM Resolution (1889) is being fetched; right now:

````
        [bibliography]
        == Bibliography
        * [[[a1,CGPM Résolution 1889-00]]]
        * [[[a2,CIPM Décision 2016-01]]]
````

is not being recognised, and is being passed through as unrecognised:

`````
         <bibliography>
           <references id='_' normative='false' obligation='informative'>
             <title>Bibliography</title>
             <bibitem id='a1'>
               <formattedref format='application/x-isodoc+xml'/>
               <docidentifier type='BIPM'>CGPM Résolution 1889-00</docidentifier>
               <docnumber>1889-00</docnumber>
             </bibitem>
             <bibitem id='a2'>
               <formattedref format='application/x-isodoc+xml'/>
               <docidentifier type='BIPM'>CIPM Décision 2016-01</docidentifier>
               <docnumber>2016-01</docnumber>
             </bibitem>
           </references>
         </bibliography>
       </bipm-standard>
````

**Comment by ronaldtse** [comment] 2022-06-13 11:35
> Do NOT give me different output if I request "CGPM Résolution 1889-00" or "CGPM Resolution 1889-00". Manuel and Ronald seem to assume you should: that is completely wrong. There is only one bibliographic resource, with language variants inside.

You misread what I meant. 

See above:
> The fetching syntax should allow both English and French, and retrieve the identical bibliographic item. 

The SAME item should be returned regardless of fetching syntax.

**Comment by ronaldtse** [comment] 2022-06-13 11:36
@andrew2net can you please help here?

1.
> "CGPM Résolution 1889-00" is NOT being recognised at all.

2.
> bundle exec relaton fetch "CGPM Résolution 1889-00"

This needs to return the docidentifiers of all languages.

**Comment by opoudjis** [comment] 2022-06-14 03:42
> "CGPM Résolution 1889-00" is NOT being recognised at all.

Fixed; thank you for finding the issue, @andrew2net

**Comment by andrew2net** [comment] 2022-06-14 10:42
@ronaldtse can we close this issue?

**Comment by opoudjis** [comment] 2022-06-15 02:26
No, because we need:

````
  <docidentifier type="BIPM" primary="true">CGPM Resolution (1889)</docidentifier>
  <docidentifier type="BIPM" primary="true" language="en" script="Latn">CGPM Resolution (1889)</docidentifier>
  <docidentifier type="BIPM" primary="true" language="fr" script="Latn">CGPM Résolution (1889)</docidentifier>

````

**Comment by ronaldtse** [comment] 2022-06-20 10:53
FYI @andrew2net is currently working on this.

**Comment by opoudjis** [comment] 2022-07-03 09:09
I need the docidentifier instances differentiated by language attributes. **This has not been done**:

bundle exec relaton fetch "CGPM Meeting 1"

````
<bibitem id="CGPMMeeting1">
  <fetched>2022-07-02</fetched>
  <title format="text/plain" language="en" script="Latn">1st meeting of the CGPM</title>
  <title format="text/plain" language="fr" script="Latn">1e réunion de la CGPM</title>
  <uri type="src">https://www.bipm.org/en/committees/cg/cgpm/1-1889</uri>
  <uri type="pdf">https://www.bipm.org/documents/20126/38097196/CGPM1.pdf/0ff415d6-87a2-5e23-5a1c-cadf8b8047a6</uri>
  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-en/meeting-01.yml</uri>
  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-fr/meeting-01.yml</uri>
  <docidentifier type="BIPM" primary="true">CGPM Meeting 1</docidentifier>
  <docidentifier type="BIPM" primary="true">CGPM Meeting 1</docidentifier>
  <docidentifier type="BIPM" primary="true">CGPM Réunion 1</docidentifier>
  <docnumber>CGPM Meeting 1</docnumber>
  <date type="published">
    <on>1889-09-28</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bureau International des Poids et Mesures</name>
      <abbreviation>BIPM</abbreviation>
      <uri>www.bipm.org</uri>
    </organization>
  </contributor>
  <language>en</language>
  <language>fr</language>
  <script>Latn</script>
</bibitem>
````

What I need is:

````
  <docidentifier type="BIPM" primary="true">CGPM Meeting 1</docidentifier>
  <docidentifier type="BIPM" primary="true" language="en">CGPM Meeting 1</docidentifier>
  <docidentifier type="BIPM" primary="true" language="fr">CGPM Réunion 1</docidentifier>
````

**Comment by andrew2net** [comment] 2022-07-03 12:37
@opoudjis I'm unable reproduce the issue. I get:
```sh
relaton fetch "CGPM Meeting 1"
[relaton-bipm] ("CGPM Meeting 1") fetching...
[relaton-bipm] ("CGPM Meeting 1") found CGPM Meeting 1
<bibitem id="CGPMMeeting1">
  <fetched>2022-07-02</fetched>
  <title format="text/plain" language="en" script="Latn">1st meeting of the CGPM</title>
  <title format="text/plain" language="fr" script="Latn">1e réunion de la CGPM</title>
  <uri type="src">https://www.bipm.org/en/committees/cg/cgpm/1-1889</uri>
  <uri type="pdf">https://www.bipm.org/documents/20126/38097196/CGPM1.pdf/0ff415d6-87a2-5e23-5a1c-cadf8b8047a6</uri>
  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-en/meeting-01.yml</uri>
  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-fr/meeting-01.yml</uri>
  <docidentifier type="BIPM" primary="true">CGPM Meeting 1</docidentifier>
  <docidentifier type="BIPM" primary="true" language="en" script="Latn">CGPM Meeting 1</docidentifier>
  <docidentifier type="BIPM" primary="true" language="fr" script="Latn">CGPM Réunion 1</docidentifier>
  <docnumber>CGPM Meeting 1</docnumber>
  <date type="published">
    <on>1889-09-28</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bureau International des Poids et Mesures</name>
      <abbreviation>BIPM</abbreviation>
      <uri>www.bipm.org</uri>
    </organization>
  </contributor>
  <language>en</language>
  <language>fr</language>
  <script>Latn</script>
</bibitem>
```

**Comment by ronaldtse** [comment] 2022-07-03 12:40
@andrew2net I'm on relaton-bipm 1.11.9 but seeing the same output as @opoudjis ?

**Comment by opoudjis** [comment] 2022-07-03 12:40
right, needs relaton version update from standoc

**Closed** 2022-07-03 12:51 UTC
Labels: enhancement

**Comment by andrew2net** [comment] 2022-07-03 13:31
> @andrew2net I'm on relaton-bipm 1.11.9 but seeing the same output as @opoudjis ?

@ronaldtse because the Relaton model is updated in the version 1.12

**Comment by ronaldtse** [comment] 2022-07-04 02:23
@opoudjis relaton-bipm is still locked to 1.11.9.

**Comment by opoudjis** [comment] 2022-07-04 04:38
Yes, release is tonight.
