### ISSUE TITLE
Compilation failure upon BIPM auto-fetch reference

### ISSUE THREAD

**Issue by manuel489** [relaton/relaton-bipm#8] opened 2020-12-11 16:19 UTC
I'm trying to auto-fetch this reference:

````
* [[[JCGM1002008,BIPM JCGM 100:2008]]], Evaluation of measurement data -- Guide to the expression of uncertainty in measurement (GUM). Joint Committee for Guides in Metrology.
````

and I get this message:

````
...

[relaton-bipm] ("BIPM JCGM 100") fetching...
C:/tools/ruby25/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://raw.githubusercontent.com/relaton/relaton-data-bipm/master/data/jcgm 100.yaml (URI::InvalidURIError)
        from C:/tools/ruby25/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
        from C:/tools/ruby25/lib/ruby/2.5.0/uri/common.rb:237:in `parse'
        from C:/tools/ruby25/lib/ruby/2.5.0/uri/common.rb:743:in `URI'

...
````

Maybe I'm not using the correct ID?

**Comment by andrew2net** [comment] 2020-12-12 13:01
@manuel489 
1. This issue was fixed in version 1.6.1 https://github.com/metanorma/bipm-si-brochure/issues/49 it isn't clear form the log which vestion do you use.
2. The document "BIPM JCGM 100" doen't exist in the [repossitory](https://github.com/relaton/relaton-data-bipm) yet.

**Comment by manuel489** [comment] 2020-12-12 13:11
Hi @andrew2net 

> This issue was fixed in version 1.6.1 metanorma/bipm-si-brochure#49 it isn't clear form the log which vestion do you use.

My relaton-bipm version is 1.7.0

> The document "BIPM JCGM 100" doen't exist in the repossitory yet.

Ok, I wanted to refer to this [document](https://www.bipm.org/utils/common/documents/jcgm/JCGM_100_2008_E.pdf). So, did I use the wrong ID or we can't auto-fetch JCGM documents yet?

**Comment by andrew2net** [comment] 2020-12-12 16:04
> > This issue was fixed in version 1.6.1 [metanorma/bipm-si-brochure#49](https://github.com/metanorma/bipm-si-brochure/issues/49) it isn't clear form the log which vestion do you use.
> 
> My relaton-bipm version is 1.7.0
> 
> >

@manuel489 I can't reproduce this issue. The piece of error message you provided doesn't contain the line of relaton-bipm where the error ocurs. Could you show the full text of the error message?

> Ok, I wanted to refer to this [document](https://www.bipm.org/utils/common/documents/jcgm/JCGM_100_2008_E.pdf). How can we auto-fetch JCGM documents?

It needs to extract the metadata from the "BIPM JCGM" document and put it into https://github.com/relaton/relaton-data-bipm/tree/master/data as `BIPM-JCGM.yaml` file.
Unfotunatelly I don't khow how to map the text from the document to the YAML structure. Maybe @ronaldtse knows?

**Comment by manuel489** [comment] 2020-12-12 16:29
> @manuel489 I can't reproduce this issue. The piece of error message you provided doesn't contain the line of relaton-bipm where the error ocurs. Could you show the full text of the error message?

You are right! I was compiling with relaton-bipm 1.5.0 indeed. I thought I was using 1.7.0 because it is listed in my gem list. I performed a `bundle update` and no issues now. Thanks @andrew2net ! Closing.

**Comment by ronaldtse** [comment] 2020-12-13 14:53
Has the failure has actually been resolved? @andrew2net says that the "JCGM 100" document is not available via auto-fetch.

JCGM is technically a different organization than BIPM (BIPM is the secretariat of JCGM, JCGM is a coordination entity that has 8 members). JCGM also only has a handful of 6 documents. They will need some modeling although they mostly map to ISO structure.

In order to make JCGM documents citable we need to include them in something like `relaton-bipm` or `relaton-jcgm` (a similar decision is to be done for Metanorma, too). Perhaps easier to have them in `relaton-bipm`? Thoughts @andrew2net ?

**Comment by manuel489** [comment] 2020-12-13 15:24
> Has the failure has actually been resolved?

**Closed** 2021-07-02 15:21 UTC
Labels: bug
